name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --tag todo-app:test --target test .
    - run: docker run --env-file .env.test todo-app:test

  deploy:
    name: Push to Docker Hub trigger app service deploy 
    runs-on: ubuntu-latest
    needs: build
    # added the new branch exercise 10
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-11' || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - run: echo hello deploy!
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - run: docker build --tag ${{secrets.DOCKER_USERNAME}}/todo-app:prodlatest --target production .
      - run: docker push ${{secrets.DOCKER_USERNAME}}/todo-app:prodlatest
      - run: curl -dH -X POST '${{ secrets.AZURE_WEBHOOK }}'

